### PR TITLE
Handle new "Already up to date" msg from Git

### PR DESCRIPTION
**Pull request by blueyed**
CI / Travis is failing currently.

### CODE REVIEW

**Comment by blueyed** [comment]
@justinmk 
Please review + merge, since CI is currently broken because of this.

**Comment by junegunn** [comment]
Oh, do you know when they changed the message?

**Comment by blueyed** [comment]
Oh, no - I have not investigated too much.  IIRC it was not so easy to find from the git log, but should be possible, of course.

**Comment by junegunn** [comment]
Merged, thanks. And sorry for the delay.

**Pull request merged**
