### PR TITLE
Use iconv() only if +iconv is enabled.

### PR DESCRIPTION
**Pull request by janlazo**
+iconv or +iconv/dyn are required for iconv().

Close https://github.com/junegunn/vim-plug/issues/920

cc @DervishD

### CODE REVIEW

**Comment by DervishD** [comment]
Thanks a lot for the fix, Jan ;)

Still, there's a problem on MY side, not vim-plug's fault, because for some reason my Vim doesn't load libiconv. That means my `iconv()` is only partially working.

Also, that means my `has('iconv')` will return 0 anyway, and as far as I know **there's NO `has('iconv/dyn')`** so your fix has no effect anyway.

This said, the good news (for you) is that really no fix is needed, it was my fault from the beginning, but I discovered it just minutes ago, so I'm very sorry for having reported a non-existing bug.

And again, this said, I think that the code would be cleaner if the tests for `multi_byte` and `iconv` were separated with two different error messages, because right now the end user doesn't know if the problem comes from `iconv` or `multi_byte`, making more difficult to fix the issue. It took me some time to determine my problem was `iconv` and not `multi_byte`.

Other than that, again I'm VERY sorry, Jan.

**Comment by janlazo** [comment]
`+multi_byte` is enabled on build time so it's likely enabled on Windows. It's a sanity check. `+iconv` is the bigger issue because there's no way to easy way to check if `iconv()` works as intended. `iconv()` can work without `+iconv` or `iconv.dll`.

Thanks for bringing this up.

**Comment by janlazo** [comment]
@junegunn Another update for fzf.

**Comment by DervishD** [comment]
Thanks for the fix! Well, it's not a fix, it's really a workaround for systems like mine, with a non-functioning libiconv, but thanks for taking the burden of making vim-plug work in those systems.

**Comment by janlazo** [comment]
It works on my machine :tm: so it's good to go.

**Pull request merged**
