### PR TITLE
Disable Ruby parallel installer on Windows.

### PR DESCRIPTION
**Pull request by vaibhavsagar**
References #81

### CODE REVIEW

**Comment by vaibhavsagar** [comment]
I'll finally be able to remove this snippet from my `.vimrc`, and you'll be able to remove it from the wiki:
```vim
if (has('win32') || has('win64'))
    let g:plug_threads=1
endif
```

**Comment by junegunn** [comment]
The Ruby installer on Windows does work even though the experience is suboptimal. We may decide to make Ruby installer an "opt-in" feature (e.g. only when `g:plug_threads` is set, or when the number of threads is explicitly specified; `:PlugInstall 8`) but I don't want to permanently disable it. Also, there are conditional branches in the Ruby code for Windows, so even if I'm going to disable it altogether, I'm not going to do it without properly cleaning up the code.

I'll let you know of the progress. Thanks.

**Comment by vaibhavsagar** [comment]
That's definitely a better solution, thanks for the quick response!

**Comment by junegunn** [comment]
So here it goes, now the default number of threads on Windows is 1. I also updated the wiki page. Thanks for your suggestion.

**Comment by vaibhavsagar** [comment]
Thank you!

**Pull request closed without merging**
