### PR TITLE
Refactor Python Command & .travis.yml

### PR DESCRIPTION
**Pull request by starcraftman**
A few highlights:
* ~~Change from time.sleep to using a thread that blocks & join it. Should reduce cpu polling problem and make it faster.~~
* A lot of style improvements in the Command class and surrounding code.
* Change travis to use env instead of many ruby versions. Makes it easier to see what build broke as env can be 'nox', 'python', 'python3', or 'ruby'. Also, I think the script reads easier.

Need to spend more time investigating the time.sleep alternative. For now, I'll just increase the sleep to reduce load.

### CODE REVIEW

**Comment by starcraftman** [comment]
@junegunn Any objections re travis? Otherwise, don't think there's anything you'd be bothered by.

**Comment by starcraftman** [comment]
Hmmm, seems to have an impact on KeyboardInterrupt support, will have to look into that. Otherwise seems no issue.

**Comment by junegunn** [comment]
Looks good to me. Love the new travis.yml. I can read and write basic Python, but I don't know well about "good style", so I'll leave that up to you. Just please make sure that there's no regression in the cases that are not (or cannot effectively) covered by the Vader test scenario, user interaction, timeout, etc. You can merge when you think it's ready.

**Comment by starcraftman** [comment]
@junegunn Ok then, seems to have a small bug regarding thread shutdown that occurs once in a while. Just need to figure it out via logs then it should be good to go.

**Comment by starcraftman** [comment]
All done and passing my tests now. Pushing that merge button.

**Pull request merged**
