### PR TITLE
Add operating system specific plugins and options section

### PR DESCRIPTION
**Pull request by herrbischoff**
Looking at #137 and #197, it could be helpful to have a more specific example in the documentation, especially one with robust OS detection.

### CODE REVIEW

**Comment by junegunn** [comment]
After those discussions, we added a section to the wiki page that deals with the issue in depth. See https://github.com/junegunn/vim-plug/wiki/faq#conditional-activation

So, instead of having another section on the README page for that, I'll try to find a nice example to add to [the current set of examples](https://github.com/junegunn/vim-plug#example).

Regarding your examples, I would advise against using `system()` function in vimrc unless it's absolutely necessary since it can increase the startup time by a few milliseconds. Instead, one should see if it's possible to do the same with `has('some_feature')` or `exists('$ENV_VARIABLE')`.

Anyway, thanks for the suggestion.

**Comment by herrbischoff** [comment]
Alright, I did not see the FAQ page. Good idea with adding to the examples.

Regarding the use of `has()`, according to `:h feature-list`, Vim does not have a built-in capability to check for the OS it's running on apart from `mac`, `macunix`, `unix`, `win32`, `win32unix` and `win64`. That distinction is rather coarse for this particular use case.

**Comment by junegunn** [comment]
You're right, `has()` may not suffice in those cases. In this particular case, `executable('gmake')` is a good alternative. Or I would probably just use `Plug 'Shougo/vimproc', { 'do': 'gmake || make' }`.

**Comment by junegunn** [comment]
`Plug 'Shougo/vimproc', { 'do': executable('gmake') ? 'gmake' : 'make' }`.

**Pull request closed without merging**
