### PR TITLE
Add hint for Neovim configuration path

### PR DESCRIPTION
**Pull request by beatrupp**

### CODE REVIEW

**Comment by junegunn** [comment]
Thanks, I'd like to suggest changing it to

```markdown
Add a vim-plug section to your `~/.vimrc` (or `~/.config/nvim/init.vim` on Neovim):
```

(Please update your commit instead of making another one)

**Comment by junegunn** [comment]
:)
Can you squash the commits into one?

**Comment by starcraftman** [comment]
The XDG specification strikes again!

Also, just to be technically correct with English, it should read `for Neovim`.  So...

`Add a vim-plug section to your `~/.vimrc` (or `~/.config/nvim/init.vim` for Neovim):`

Gotta live up to Futurama bureaucrats :)

**Comment by junegunn** [comment]
@starcraftman :+1:

**Comment by junegunn** [comment]
@beatrupp Great! But can you update your commit once again according to @starcraftman's suggestion? Thanks for your persistence.

**Comment by beatrupp** [comment]
Hehe, I was not paying attention to the details I see :)

**Comment by junegunn** [comment]
Merged, thanks!

**Comment by starcraftman** [comment]
@beatrupp Thanks for contributing.

**Pull request merged**
