### PR TITLE
Support non-master default branch

### PR DESCRIPTION
**Pull request by mattn**
https://github.blog/changelog/2020-08-26-set-the-default-branch-for-newly-created-repositories/

GitHub will be change the default branch to `main` for newly created repository. vim-plug use `master` branch for the default. This change look current branch name from HEAD/ref.

### CODE REVIEW

**Comment by mattn** [comment]
This change add number of calls of git command. I suggest to merge #937

https://github.com/junegunn/vim-plug/pull/937

**Comment by junegunn** [comment]
Thanks, but this PR is missing `s:git_get_branch`.

**Comment by mattn** [comment]
@junegunn Thank you. What still wrong?

https://travis-ci.org/github/junegunn/vim-plug/jobs/721704596

**Comment by junegunn** [comment]
Failing test cases are marked with `(X)`.

We have a very comprehensive set of test cases testing every aspect of vim-plug. And obviously this pull request breaks existing test cases written with some assumptions of how vim-plug should behave. We would have to also update existing test cases accordingly.

**Comment by junegunn** [comment]
Let me see if I can fix them.

**Comment by junegunn** [comment]
I've managed to make the existing test cases pass, though I'm not 100% sure if reading `.git/refs/remotes/origin/HEAD` is the correct way to get the default branch of origin. Please review the updated code.

**Comment by mattn** [comment]
Thank you. Looks good to me.

**Comment by leitzler** [comment]
Thanks for this PR @mattn! As far as I understand, vim-plug will now fetch the default branch when adding a new plugin.

Since a lot of repositories also follow GitHubs rename instructions I suggest that vim-plug also run `git remote set-head origin -a` each update to ensure that the remote default branch isn't stale.

Thoughts?

**Comment by mattn** [comment]
I'm okay. Any thought? @junegunn

**Pull request merged**
