### PR TITLE
Clarify the usage instructions

### PR DESCRIPTION
**Pull request by LaserMoai**
This should reduce probability of issues with unexpected overrides.

### CODE REVIEW

**Comment by stappersg** [comment]
This simple pull request got today, so after eightteen months, yes that is one-and-a-half-year,  a first comment.

The *pull request* is about getting
```
Add a vim-plug section to your `~/.vimrc` 
```
into
```
Add a vim-plug section to the top of your `~/.vimrc` 
```
in the `README.md`.


The benefit of **closing** this  *PR*, either by *merge* or by *reject*, is that doesn't drain further human energy.

Yes, indeed, open pull requests do waste resources.  So if you have the power of closing this *pull request*, take your responsebilty and close it.

Thanks.

**Comment by junegunn** [comment]
@stappersg So what is your opinion on this? Is having the section on the top of vimrc required, or is it just recommended way of organizing the configuration? If it's the latter, why is it better? What are the pros and cons of having or not having it on the top of vimrc? If the maintainer does not have all the time and energy, or motivation to think about the implications of the change, the pull request is left open. If you want it resolved, you can contribute your ideas.

**Comment by stappersg** [comment]
Oo, that triggers
> A opinion is like an asshole, everbody has one.      -- Dirty Harry ( The Dead pool )


And my personal opinion:

It is **good** that there is **now**
* If the maintainer does not have all the time and energy, or motivation to think about the implications of the change, the pull request is left open.
*  If you want it resolved, you can contribute your ideas.

in this issue **plus** the questions
*  Is having the section on the top of vimrc required, or is it just recommended way of organizing the configuration?
* If it's the latter, why is it better?
* What are the pros and cons of having or not having it on the top of vimrc?

**Comment by LaserMoai** [comment]
Sorry, I don't remember what was the problem I was having because of a non-standard vimrc position. It probably had something to do with keyboard remapping plugins. Since both [the tutorial](https://github.com/junegunn/vim-plug/wiki/tutorial) and Vundle's readme instruct this I thought this made sense to instruct in the readme. Feel free to reject the PR.

**Comment by stappersg** [comment]
> Feel free to reject the PR.

For what its worth

 @LaserMoai has the power to close this pull request

**Comment by LaserMoai** [comment]
I think I probably just modified a plugin setting before the vim-plug section.

**Pull request closed without merging**
