### PR TITLE
generate documentation from script

### PR DESCRIPTION
**Pull request by chrisbra**
#388

### CODE REVIEW

**Comment by chrisbra** [comment]
don't understand why travis failed, as I did not change the plugin at all.

**Comment by junegunn** [comment]
Well, the failure is due to the test script appending some code to plug.vim for clearing the internal data structure during the test. Yeah, It's hacky and can have some improvement, but I just didn't want to add some API just for test.

Anyway, thanks for putting this together but I don't think I'm in favor of this approach.
- First of all, the markdown document you attached is not up-to-date.
- `plug.vim` is already pretty long, and we're adding 200 more lines here.
- It's basically two files of completely different types concatenated and it doesn't feel like an elegant solution. The merged file is not editor-friendly and will be difficult to maintain.
- The help file is not updated on `PlugUpgrade` which can be confusing.
- If we're going to tell the user to use an extra script for installing the documentation, what's the point of having the text included in plug.vim? I would just separately provide plug.txt in this repository and make `PlugUpgrade` or some other command handle that.

We'll continue the discussion, but this is not the approach I have in mind.

**Comment by chrisbra** [comment]
I don't agree with alll those points, but oh well..

**Comment by junegunn** [comment]
So you think vimscript file concatenated with a markdown file is an elegant solution? Hmm, we'll have to agree to disagree then.

**Comment by chrisbra** [comment]
No, I think when distributing a single plugin.vim file, this is the only possibility to keep documentation. But nevertheless my approach did not work, since I introduced a new file, which would not be available after the typical curl... installation. 
BTW: it is not that uncommon, to distribute documentation included with code. perl pod does exactly this.

**Comment by junegunn** [comment]
Okay thanks for the clarification. Looks like I somehow misinterpreted your words, sorry about that. Yes, perl pod is a good example but we both know that the situation here is different from that. If we don't have to provide help in vimdoc format, we can do similar stuff with the header comment as I mentioned in #388.

**Comment by vheon** [comment]
If I can give my 2 cents:

- Ship the vimdoc documentation as the header of the plug.vim file surrounded by some delimiter like `STARTDOC` `ENDDOC`.
- Instead of making a separate vim script add a command like `PlugGenerateDoc` to create the `~/.vim/doc/plug.txt` file and generate the helptags
- On `PlugUpgrade` simply rerun the `PlugGenerateDoc` automatically if the file is already there (i.e. the user already allow vim-plug to write the documentation)

I find myself from time to time to want the vim-plug documentation and I would prefer to have it right inside vim instead of going to the browser (not that is that of a big deal anyway, but oh well...)

**Pull request closed without merging**
