### PR TITLE
Add Flatpak installation instructions to README.md

### PR DESCRIPTION
**Pull request by returntrip**
I have added installation instructions for those users that use neovim through Flatpak.

### CODE REVIEW

**Comment by kkga** [comment]
Installing into `~/.var/app/io.neovim.nvim/data/nvim/site/autoload/plug.vim` still doesn't make it work in my case. What else might be missing?

**Comment by returntrip** [comment]
@kkga not home but I think this should help:

## Neovim Flatpak
- `init.vim` to be created in `~/.var/app/io.neovim.nvim/config/nvim/` 

### vim-plug
- Install `plug.vim` using:

```
curl -fLo ~/.var/app/io.neovim.nvim/data/nvim/site/autoload/plug.vim --create-dirs     https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```

- Add the following, as a minimum to `init.vim`:

```
call plug#begin()
call plug#end()
```

**Comment by kkga** [comment]
Thanks for the response, works great :+1: 
For some reason I symlinked my init.vim into `~/.var/app/io.neovim.nvim/config/` instead of `~/.var/app/io.neovim.nvim/config/nvim/` :man_facepalming:

**Comment by liuhaowen478** [comment]
This is extremely helpful for me.
Can somebody merge it?

**Comment by janlazo** [comment]
Verified on Ubuntu 16.04 using the default instructions at https://flatpak.org/setup/Ubuntu/ and https://flathub.org/apps/details/io.neovim.nvim.

**Comment by andmalc** [comment]
The commit missed this line:

 init.vim to be created in ~/.var/app/io.neovim.nvim/config/nvim/

**Pull request merged**
