### PR TITLE
Pass empty string for credential.helper

### PR DESCRIPTION
**Pull request by mattn**
Current implementation does not fix on Windows cmd.exe

https://github.com/junegunn/vim-plug/pull/1026 or https://github.com/junegunn/vim-plug/issues/1031

### CODE REVIEW

**Comment by mattn** [comment]
Hmm, this change also not fix the issue.

**Comment by mattn** [comment]
I have no idea.

image

**Comment by mattn** [comment]
I figure out the issue. Will update commits.

**Review by junegunn — APPROVED** [review]

**Comment by junegunn** [comment]
Merged, thanks!

**Pull request merged**
