### PR TITLE
Tuning4neovim

### PR DESCRIPTION
**Pull request by stappersg**
Hi,

Seeing _vim_ specific instructions in `plug.vim` did confuse me.

This pull request is an attempt to get less _vim noise_ for neovim users.

### CODE REVIEW

**Comment by pmav99** [comment]
By the way instead of having to maintain two sets of `*.vim` files, it might make sense just to improve the example in the documentation. E.g.

``` vim
" Bootstrap Plug {
  " Set the appropriate paths for Plug
  " PLUG_AUTOLOAD_PATH is a script variable because we only need to bootstrap
  " Plug on first run.
  " PLUG_DATA_DIR is a global because we might want to use it in .gvimrc etc
  if has('nvim')
    let s:PLUG_AUTOLOAD_PATH = stdpath('data') . '/site/autoload/plug.vim'
    let g:PLUG_DATA_DIR = stdpath('data') . '/plugged'
  else
    let s:PLUG_AUTOLOAD_PATH = $HOME . '/.vim/autoload/plug.vim'
    let g:PLUG_DATA_DIR = $HOME . '/.vim/plugged'
  endif

  " Install plug
  if !filereadable(s:PLUG_AUTOLOAD_PATH)
    silent execute '!curl -fLo ' . s:PLUG_AUTOLOAD_PATH . ' --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
  endif
  unlet s:PLUG_AUTOLOAD_PATH
" Bootstrap Plug }

" Plugins {
  call plug#begin(g:PLUG_DATA_DIR)
    Plug 'itchyny/lightline.vim'                                                    " Status Line
    Plug 'scrooloose/nerdcommenter'                                                 " Comments
    Plug 'mbbill/undotree'                                                          " Undo
    Plug 'editorconfig/editorconfig-vim'
    Plug 'tpope/vim-eunuch'
    Plug 'tpope/vim-repeat'
    Plug 'tpope/vim-surround'
    if filereadable("/usr/bin/fzf")                                                 " Fuzzy
      Plug 'junegunn/fzf.vim'
    endif
  call plug#end()

  " if we want to define more plugins in a different file we can do it like this
  call plug#begin(g:PLUG_DATA_DIR)
    Plug 'morhetz/gruvbox'
  call plug#end()
" Plugins }

```

**Comment by junegunn** [comment]
Sorry, I do not like this approach.

**Comment by pmav99** [comment]
@junegunn How about the bootstrap code in my previous message? Would you accept a PR with that?

**Comment by junegunn** [comment]
I can update [the wiki page](https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation), but I don't want to present the code upfront in the README page, because some people will recognize it as necessary boilerplate code when it's just optional. Also, both Vim and Neovim users on Windows platform will complain that the code doesn't run on their system, unless we provide code for 4 different sets of paths. I'd like to keep README page as short as possible.

**Comment by pmav99** [comment]
sure, no problem

**Pull request closed without merging**
